name: ink_wander
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.3+8

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  google_generative_ai: ^0.4.3
  google_mobile_ads: ^5.1.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - shorebird.yaml

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Slabo27px
      fonts:
        - asset: assets/fonts/Slabo27px-Regular.ttf
    - family: Merienda
      fonts:
        - asset: assets/fonts/Merienda-Regular.ttf
    - family: Margarine
      fonts:
        - asset: assets/fonts/Margarine-Regular.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf
    - family: BodoniModa
      fonts:
        - asset: assets/fonts/BodoniModa-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
      
flutter_native_splash:
  background_image: "assets/images/splash.jpeg"  
  android: true                                 
  ios: true                                     
  web: false                                    

