// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtrMxCXRfXT40x9NXAhjdyotk6f3HydfQ',
    appId: '1:69719377534:web:8ba1e72919a83a7f91fa2f',
    messagingSenderId: '69719377534',
    projectId: 'ink-wander',
    authDomain: 'ink-wander.firebaseapp.com',
    storageBucket: 'ink-wander.appspot.com',
    measurementId: 'G-B72QJH1BXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASqwuzTK61ky8pSNTIWr8qU2yfpWV1WBk',
    appId: '1:69719377534:android:f2f103a222e146c791fa2f',
    messagingSenderId: '69719377534',
    projectId: 'ink-wander',
    storageBucket: 'ink-wander.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpvhrtELhkFJeLdtwaDri1TTsVBvBV2eo',
    appId: '1:69719377534:ios:37ac2b60e12f294191fa2f',
    messagingSenderId: '69719377534',
    projectId: 'ink-wander',
    storageBucket: 'ink-wander.appspot.com',
    androidClientId: '69719377534-ftj9jjcdvef1jt108ueh04uhs5ebm1i5.apps.googleusercontent.com',
    iosClientId: '69719377534-7cvv8csvqo8c79l9d98osjge43j5r2lh.apps.googleusercontent.com',
    iosBundleId: 'com.example.inkWander',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpvhrtELhkFJeLdtwaDri1TTsVBvBV2eo',
    appId: '1:69719377534:ios:37ac2b60e12f294191fa2f',
    messagingSenderId: '69719377534',
    projectId: 'ink-wander',
    storageBucket: 'ink-wander.appspot.com',
    androidClientId: '69719377534-ftj9jjcdvef1jt108ueh04uhs5ebm1i5.apps.googleusercontent.com',
    iosClientId: '69719377534-7cvv8csvqo8c79l9d98osjge43j5r2lh.apps.googleusercontent.com',
    iosBundleId: 'com.example.inkWander',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtrMxCXRfXT40x9NXAhjdyotk6f3HydfQ',
    appId: '1:69719377534:web:8272f9ce5b7adc5191fa2f',
    messagingSenderId: '69719377534',
    projectId: 'ink-wander',
    authDomain: 'ink-wander.firebaseapp.com',
    storageBucket: 'ink-wander.appspot.com',
    measurementId: 'G-3JWKWXBXLT',
  );
}
